# Site settings
title: The Code Recipe
email: contact@thecoderecipe.com
description: > # this means to ignore newlines until "baseurl:"
  The Code Recipe aims at providing useful articles and tools to make programming more pleasant. It
  is not limited to a particular platform or language.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.thecoderecipe.com" # the base hostname & protocol for your site
twitter_username: fwouts
github_username:  fwouts

# Build settings
markdown: kramdown
